---
title: "03_lm-condition-effects"
format: html
echo: false
message: false
warning:  false
---

```{r}
library(here)
library(tidyverse)
library(dotwhisker)
library(broom)
library(ggpubr)
library(brms)

source("R/visualise/colour-palettes.R")
source("R/helper-functions/lm-functions.R")

Bayesian <- TRUE
run_models <- FALSE

```

```{r}
# load before and after data separately
load(here("data/magpie/original/combined/before.Rdata"))
load(here("data/magpie/original/combined/after.Rdata"))

# load before, after, change combined data
load(here(
  "data/magpie/processed/combined/survey-before-after-change.Rdata"
))
```


```{r}


# get variable names
before_questions <- colnames(d_before)
after_questions <- colnames(d_after)

# questions asked at the end related to their overall experience
after_only_questions <- c("PropLiked",
                          "PropTrolls",
                          "PropAligned",
                          "MagpieSimilarity",
                          "OverallExperience")

# questions relating to their feelings towards republicans/democrats
change_partisan <- c(after_questions[grepl("Dem", after_questions) |
                                       grepl("Rep", after_questions)], "AffPol")


# questions pertaining to political beliefs
change_beliefs <- after_questions[grepl("Belief", after_questions) != grepl("Extreme", after_questions)]

# belief questions transformed to mark non partisan extremity
change_beliefs_extreme <- after_questions[grepl("Extreme", after_questions)]

# questions asking how politically divided they think the us is
change_consensus <- after_questions[grepl("Consensus", after_questions)]

# questions asking how extreme their own beliefs are relative to the population
change_relative <- after_questions[grepl("Relative", after_questions)]

# questions asking how extreme their own beliefs are relative to the population
change_trust <- after_questions[grepl("Trust", after_questions)]
change_trust <- change_trust["WVSTrust" != change_trust]

# get the number of comparisons for bonferroni adjustment
n_comparison = 17 + length(after_only_questions)
```

# **Post experiment experience questions**

```{r}
#| fig.width: 13
#| fig.height: 15
variable_groups <- after_only_questions
titles <- c(
    "A. How much did they enjoy the experience overall?",
  "B. What proportion of other users did they like?",
  "C. What proportion of accounts did they think were trolls?",
  "D. How aligned did they think they were compared to the rest of the sample politically?",
  "E. How similar was the experiment to normal social media?"
)
x_labs_lm <- c(
    "< 0 = enjoyed less compared to control",
  "<  0 = liked fewer other users compared to control",
  "< 0 = fewer trolls compared to control",
  "< 0 = less politicaly aligned compared to control",
  "< 0 = experience less similar compared to control"
)

x_labs_bar <- c(
    "Lower = less enjoyment",
  "Lower = liked fewer participants",
  "Lower = fewer trolls",
  "Lower = less aligned politically",
  "Lower = less similar to social media"
)

# scale data to between 0 and 1 
d_before_after_change_scale01 <- d_before_after_change %>%
  mutate(across(
    where(is.numeric) & 
      (ends_with("Before") | ends_with("After")|any_of(after_only_questions)),
    scale_to_01
  ))


d_lm <- d_before_after_change_scale01
d_bar <- d_before_after_change

p_list_survey_qs <- plot_lm_and_bar(variable_groups, x_labs_lm,x_labs_bar, titles, d_lm, d_bar, change = FALSE, Bayesian = Bayesian, run_models = run_models)
p_survey_qs <- ggarrange(plotlist = p_list_survey_qs,
                         ncol = 1,
                         common.legend = TRUE,
                         heights = c(2.1,1.5,1.5,1.5,1.5)
)
p_survey_qs 
file = paste0("R/visualise/plots/combined-bar-lm-post-survey-Bayes-",Bayesian,".png")
ggsave(filename = file, width = 23, height = 22, units = "cm", plot = p_survey_qs) # roughly a4 size
```
## Follow up enjoyment with prior beliefs by condition

```{r}
d_before_after_change %>%
  split(.$Condition) %>%
  map(~ cor.test(.x$BeliefBefore, .x$OverallExperience))

```
# **Before/After Change variables**

```{r}
#| fig.width: 13
#| fig.height: 15
variable_groups <- list(change_beliefs,
                        change_consensus,
                        change_relative,
                        "TrustOverall",
                        "AffPol"
                        )
titles <- c(
  "A. Political beliefs", 
  "B. Perceptions of conesnsus",
  "C. Perceived own beliefs relative to population",
  "D. Overall trust in government and other institutions",
  "E. Affective polarisation"
)
#: 'Where would you classify your overall political beliefs, relative to most people in the US?'
#'To what extent do you think that most people in the US generally agree with each other about their overall political beliefs?'
x_labs_lm <- c(
  "< 0 = more left wing than control",
  "< 0 = less belief there is a consensus compared to control",
  "< 0 = beliefs more left wing relative to population compared to control",
  "< 0 = less trusting than control",
  "< 0 = less polarised than control"
)

x_labs_bar <- c(
  "< 0 = left wing change",
  "< 0 = reduced belief that there is a consensus",
  "< 0 = beliefs became more left wing relative to population",
  "< 0 = became less trusting",
  "< 0 = became less polarised"
)


p_list_change_vars <- plot_lm_and_bar(
  variable_groups,
  x_labs_lm,
  x_labs_bar,
  titles,
  d_lm,
  d_bar,
  change = TRUE,
  ytext = TRUE,
  ylim = c(-10, 10),
  xlim = c(-0.5,0.5),
  Bayesian = Bayesian,
  run_models = run_models,
  title_size = 20,
  base_size = 17
)
p_change_vars <- ggarrange(
  plotlist = p_list_change_vars,
  ncol = 1,
  heights = c(6, 5, 5, 1.7, 1.7, 5)
)
p_change_vars
file = paste0("R/visualise/plots/combined-bar-lm-change-vars-Bayes-",Bayesian,".png")
ggsave(filename =file, width = 35, height = 45, units = "cm", plot = p_change_vars) # roughly a4 size

```


```{r}
#| fig.width: 13
#| fig.height: 15
variable_groups <- list(
  change_trust,
  change_partisan
)

titles <- c(
  "Trust Measures",
  "Affective Polarisation Measures"
)

x_labs_lm = c(
  "< 0 = trust less than control",
  "< 0 = less polarised than control"
)

x_labs_bar = c(
  "< 0 = became less trusting",
  "< 0 = became less polarised"
)

p_list_aff_trust <- plot_lm_and_bar(
  variable_groups,
  x_labs_lm,
  x_labs_bar,
  titles,
  d_lm,
  d_bar,
  change = TRUE,
  ytext = TRUE,
  ylim = c(-10, 10),
  #xlim = c(-0.5,0.5),
  by_topic = FALSE,
  Bayesian = Bayesian,
  run_models = run_models
)
p_aff_trust <- ggarrange(
  plotlist = p_list_aff_trust,
  ncol = 1,
  heights = c(1,2)
)
p_aff_trust
file = paste0("R/visualise/plots/combined-bar-lm-aff-trust-Bayes-",Bayesian,".png")
ggsave(filename = file, width = 30, height = 37, units = "cm", plot = p_aff_trust) # roughly a4 size

```

## Initial values of measures

### Change variables 

```{r}
# check priors of trust measures 
d_before %>%
  pivot_longer(values_to = "Value", names_to = "Variable", cols = c(change_beliefs, change_consensus, change_relative, change_trust, change_partisan)) %>%
  group_by(Variable) %>%
  summarise(Mean = round(mean(Value),2), SD = round(sd(Value),2))
```

## Experience variables
```{r}
d_after %>%
  pivot_longer(values_to = "Value", names_to = "Variable", cols = after_only_questions) %>%
  group_by(Variable) %>%
  summarise(Mean = round(mean(Value),2), SD = round(sd(Value),2))
```

```{r}
print(paste0("Mean initial overall trust: ", round(mean(d_before$TrustOverall),2), " SD: ", round(sd(d_before$TrustOverall))))
```


## Follow up unintuitive trust 

```{r}
# check priors of trust measures 
d_before %>%
  select(Condition, starts_with("Trust"), Subject) %>%
  pivot_longer(values_to = "Value", names_to = "Trust_Type", cols = starts_with("Trust")) %>%
  group_by(Condition, Trust_Type) %>%
  summarise(Mean = mean(Value))

```

# Effect of posts seen on measures

```{r}
############################################################
# Enhanced Model Running Function
############################################################

runMultipleModels <- function(data, 
                              outcome, 
                              control, 
                              predictors,
                              Bayesian = FALSE,
                              family = gaussian(),
                              save_models = FALSE,
                              model_dir = "models",
                              load_existing = FALSE,
                              cores = 2) {
  
  # Create model directory if saving/loading
  if (save_models || load_existing) {
    if (!dir.exists(model_dir)) {
      dir.create(model_dir, recursive = TRUE)
    }
  }
  
  purrr::map_dfr(predictors, function(pred) {
    
    rhs <- paste(c(control, pred), collapse = " + ")
    formula_str <- paste0(outcome, " ~ ", rhs)
    model_name <- paste0(outcome, "_", gsub("[^[:alnum:]]", "_", pred))
    model_path <- file.path(model_dir, paste0(model_name, ".rds"))
    
    # Check if we should load existing model
    if (load_existing && file.exists(model_path)) {
      message("Loading existing model: ", model_name)
      m <- readRDS(model_path)
      
      if (Bayesian) {
        summ_m <- summary(m)$fixed %>%
          mutate(model = formula_str) %>%
          rownames_to_column(var = "term") %>%
          rename(estimate = Estimate)
        return(summ_m)
      } else {
        return(broom::tidy(m) %>% mutate(model = formula_str))
      }
    }
    
    # Fit new model
    if (Bayesian) {
      m <- brm(
        data = data,
        formula = as.formula(formula_str),
        family = family,
        cores = cores
      )
      
      if (save_models) {
        saveRDS(m, model_path)
        message("Saved model: ", model_path)
      }
      
      summ_m <- summary(m)$fixed %>%
        mutate(model = formula_str) %>%
        rownames_to_column(var = "term") %>%
        rename(estimate = Estimate)
      
      return(summ_m)
      
    } else {
      m <- linear_model(outcome, rhs, data)
      
      if (save_models) {
        saveRDS(m, model_path)
        message("Saved model: ", model_path)
      }
      
      return(broom::tidy(m) %>% mutate(model = formula_str))
    }
  })
}


############################################################
# Enhanced Plotting Function
############################################################

plotMultipleModelCoeffs <- function(model_output,
                                    control_var,
                                    title = NULL,
                                    xlab = "Estimate",
                                    ylab = "Model",
                                    subtitle = NULL,
                                    legend.position = "none",
                                    ytext = TRUE,
                                    xlim = NULL,
                                    by_topic = FALSE,
                                    keywords = c("AI", "Trans", "Climate", "Israel"),
                                    n_comparisons = NULL,
                                    Bayesian = FALSE,
                                    base_size = 14,
                                    condition_colours = NULL) {
  
  # Clean data
  clean <- model_output %>%
    filter(! term %in% c("(Intercept)","Intercept")) %>%
    mutate(term = as.character(term)) %>%
    group_by(model) %>%
    mutate(has_interaction = any(str_detect(term, fixed(":")))) %>%
    ungroup() %>%
    # Remove control main effect only
    filter(!term %in% c(control_var, paste0("`", control_var, "`"))) %>%
    group_by(model, has_interaction) %>%
    filter(if (has_interaction[1]) str_detect(term, fixed(":")) else TRUE) %>%
    ungroup() %>%
    mutate(condition = case_when(
      grepl("ConditionLeft", term) ~ "Left",
      grepl("ConditionRight", term) ~ "Right",
      TRUE ~ "Not by condition"
    ))
  
  # Apply topic grouping if requested
  if (by_topic) {
    clean <- clean %>%
      mutate(
        model_clean = str_extract(model, paste(keywords, collapse = "|")),
        model_clean = if_else(is.na(model_clean), "Overall", model_clean),
        model_clean = factor(model_clean, levels = c(keywords, "Overall"))
      )
  } else {
    clean <- clean %>%
      mutate(model_clean = model)
  }
  
  # Compute Bonferroni adjusted CIs for frequentist models
  if (!Bayesian && !is.null(n_comparisons)) {
    adjusted_alpha <- 0.05 / n_comparisons
    z_crit <- qnorm(1 - adjusted_alpha / 2)
  }
  
  # Build plot
  p <- ggplot(clean, aes(x = estimate, y = model_clean, color = condition)) +
    geom_errorbar(
      aes(
        xmin = if (Bayesian) `l-95% CI` else if (!is.null(n_comparisons)) estimate - z_crit * std.error else estimate - 1.96 * std.error,
        xmax = if (Bayesian) `u-95% CI` else if (!is.null(n_comparisons)) estimate + z_crit * std.error else estimate + 1.96 * std.error
      ),
      width = 0.2,
      position = position_dodge(width = 0.6)
    ) +
    geom_point(
      aes(fill = condition),
      position = position_dodge(width = 0.6),
      size = 3,
      shape = 21,
      colour = "black",
      stroke = 0.6
    ) +
    geom_vline(xintercept = 0, linetype = "dashed", colour = "gray50") +
    labs(
      x = xlab,
      y = ylab,
      color = "Condition",
      fill = "Condition",
      title = title,
      subtitle = subtitle
    ) +
    theme_minimal(base_size = base_size) +
    theme(
      panel.grid.major.y = element_blank(),
      legend.position = legend.position,
      plot.title = element_text(hjust = 0)
    )
  
  # Apply custom colors if provided
  if (!is.null(condition_colours)) {
    p <- p +
      scale_color_manual(values = condition_colours) +
      scale_fill_manual(values = condition_colours)
  }
  
  # Apply x-axis limits if provided
  if (!is.null(xlim)) {
    p <- p + lims(x = xlim)
  }
  
  # Hide y-axis text if requested
  if (!ytext) {
    p <- p + theme(axis.text.y = element_blank())
  }
  
  return(p)
}


```

```{r}
library(here)
library(dplyr)

# Define if Bayesian 
Bayesian = FALSE

# Load data for different troll conditions
load(here("data/magpie/processed/combined/posts-seen-by-user.Rdata"))

troll_datasets <- list(
  "all_posts" = load_and_combine_data(troll = "all_posts")[["scaled"]],
  "no_troll" = load_and_combine_data(troll = "no_troll")[["scaled"]],
  "troll_only" = load_and_combine_data(troll = "only_troll")[["scaled"]]
)

# Predictors
single_param_predictors <- c(
  "Condition",
  "prop_right",
  "prop_left"
)

# Outcomes and controls
outcomes <- c(
  paste0(change_beliefs, "After"),
  paste0(change_consensus, "After"),
  paste0(change_trust, "After")
)

controls <- c(
  paste0(change_beliefs, "Before"),
  paste0(change_consensus, "Before"),
  paste0(change_trust, "Before")
)

# Loop through each troll type
for (troll_name in names(troll_datasets)) {
  
  cat("\n=== Processing:", troll_name, "===\n")
  
  # Loop through each outcome/control pair
  for (i in seq_along(outcomes)) {
    
    outcome <- outcomes[i]
    control <- controls[i]
    
    cat("  Running:", outcome, "~", control, "\n")
    
    # Run models
    output <- runMultipleModels(
      data = troll_datasets[[troll_name]],
      outcome = outcome,
      control = control,
      predictors = single_param_predictors,
      Bayesian = Bayesian
    )
    
    # Plot
    p <- plotMultipleModelCoeffs(
      model_output = output,
      control_var = control,
      title = paste0(troll_name, ": ", outcome),
      Bayesian = Bayesian
    )
    
    print(p)
  }
}
```

```{r}
load(here("data/magpie/processed/combined/posts-seen-by-user.Rdata"))

#. no filters applied 
d_posts_seen <- load_and_combine_data(troll = "all_posts")[["scaled"]]

# no troll initiated conversations
d_posts_seen_no_troll <- load_and_combine_data(troll = "no_troll")[["scaled"]]

# only troll initiated conversations
d_posts_seen_troll_only <- load_and_combine_data(troll = "only_troll")[["scaled"]]


# predictors are the same regardless of the outcomes/control
single_param_predictors <- c(
  " Condition",
  " prop_right",
  " prop_left"
)

# different parameter comparison for each outcome
outcomes <- c(paste0(change_beliefs,"After"),paste0(change_consensus,"After"),paste0(change_trust,"After"))

# controls correspond to the outcome (outcome[si] = controls[i])
controls <- c(paste0(change_beliefs,"Before"), paste0(change_consensus,"Before"), paste0(change_trust,"After"))

output <- runMultipleModels(d_posts_seen, outcomes,controls, single_param_predictors, Bayesian = TRUE)
output

plotMultipleModelCoeffs(output, control_var = "BeliefBefore", Bayesian = TRUE)
```

